# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Framework

on:
  push:
    branches: [dev]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    name: Test Framework
    uses: ./.github/workflows/workflow-test.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
